# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            NAGESH D N
tagline:          ''
description:      'Technical professional  in Datacenter/Cloud,Software Defined DataCenter (SDDC),Hyper-Converged Infrastructure (HCI), Cloud Solution Architect.'
url:              https://nageshdn.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Nagesh'
  url:            https://twitter.com/ndn9797

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache

compress_html:
  clippings: all

sass:
  sass_dir: _sass
  style: compressed



paginate: 5 # amount of posts to show
paginate_path: /page-:num/
timezone: Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


defaults:
  #_posts
  - scope:
     path: ""
     type: posts
    values:
     layout: single
     author_profile: true
     read_time: true
     comments: true
     share: true
     related: true
disqus:
  shortname: nageshdn

google_analytics: UA-111754253-1

google_site_verification : "IwCxye9SaFsyOsfw7vGNz12MYn-bOudeyzkVtZolzrk"
bing_site_verification   : "0039DC36357A94284ACD48EEC0A20F48"
#yandex_site_verification : "36298deb5ec6b694"
#naver_site_verification  :

# Custom vars

#version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/ndn97.github.io
