version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"
   
phases:
  install:
    commands:
      - apt-get update -y
      - gem install jekyll jekyll-feed jekyll-paginate  jekyll-gist jekyll-seo-tag jekyll-sitemap jekyll-gzip
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
  
