version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"
   
phases:
  install:
    commands:
      - bundle install

  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
  
