version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"
   
phases:
  install:
    commands:
      - apt-get update -y
      - gem update github-pages
      - gem install jekyll jekyll-feed jekyll-paginate  jekyll-gist jekyll-seo-tag
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
  
