version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"
   
phases:
  install:
    commands:
      - apt-get update -y
      - gem update github-pages
      - gem install jekyll jekyll-feed jekyll-paginate  jekyll-gist jekyll-seo-tag
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build

  post_build:
    commands:
      - echo "******** Uploading to S3 ********"
      - aws s3 sync --delete --size-only --cache-control max-age=7201 _site/ "s3://${BUCKET_NAME}"
      - aws cloudfront create-invalidation --distribution-id "${CLOUDFRONTDIST}" --paths "/*"
