version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"
   
phases:
  install:
    commands:
      - bundle update

  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build

artifacts:
  files:
    - '**/*'
  base-directory: '_site/'
