version: 0.2

env:
  variables:
    JEKYLL_ENV: "production"
   
phases:
  install:
    commands:
      # - gem install jekyll jekyll-feed jekyll-paginate  jekyll-gist jekyll-seo-tag
      bundle install 
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
  
