version: 0.2

env:
  variables:
SITEBUILD: "yes"
phases:
  install:
commands:
apt-get update -y
  pre_build:
commands:
gem install bundler
	bundle install
  build:
commands:
echo Build started on date
	bundle exec jekyll build
	aws s3 sync _site/ s3://www.nageshdn-draft.com
  post_build:
commands:
echo Build completed on date
